name: lincs-state-space-navigator
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pyyaml
  - jupyterlab
  - pip
  - pip:
      - cmapPy
